name: CI

on:
  push:
    branches:
      - "**"  # ✅ Run on ALL branches (not just main)
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  validate_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Determine Branch Name
        id: get_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Validate Branch Name
        run: |
          echo "Checking branch name: $BRANCH_NAME"

          # ✅ Always validate, even for new branches
          if [[ ! "$BRANCH_NAME" =~ ^KAAM-[0-9]+$ ]]; then
              echo "❌ ERROR: Invalid branch name '$BRANCH_NAME'"
              exit 1
          fi

          echo "✅ Branch name is valid."
